### ISSUE TITLE
When will the code be open source?

### ISSUE THREAD

**Issue by new-a-class** [OFSkean/FroSSL#1]
Thank you for your contribution. When will the code be open source?

**Comment by OFSkean** [comment]
Hello! We are currently preparing the repository for upload. I will have it up by this weekend, 5/18 at the latest

**Comment by new-a-class** [comment]
Thank you for your contribution again. Is the code updated?

**Comment by OFSkean** [comment]
Hello @new-a-class! Thank you for your patience, we've uploaded all of our code now that the review process is finished.
